services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Доступ к PHP через порт 8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306" # Доступ к базе данных MySQL через порт 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # Доступ к phpMyAdmin через порт 8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
